apiVersion: v1
kind: Service
metadata:
  name: go-hello-world
  labels:
    app: go-hello-world-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: go-hello-world